### ISSUE TITLE
python_path in neptune_init

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ai/neptune-r#1]
@needlecapter 

It seems that `python_path` is a required argument [here](https://github.com/neptune-ai/neptune-r/blob/master/neptune/R/neptune.R#L12):

```R
init_neptune <- function(project_name,
                        api_token = NULL,
                        python = NULL,
                        python_path) {
```

Also, does `python` require string 'conda', 'miniconda', 'venv' or an object?

**Comment by needlecapter** [comment]
python should be one of the following strings
python - use system python installation
conda - use conda env
miniconda - use miniconda env
venv - use 'normal' virtual env

python_path is required only when python is not null (it can be left as null is user uses default python or sets python before calling init_neptune)
