### ISSUE TITLE
neptune-r doesn't work in jupyter notebook

### ISSUE THREAD

**Issue by abin-tiger** [neptune-ai/neptune-r#16]
neptune-client: 0.14.3
r version: 4.1.0

```python
library(reticulate)
library(neptune)

run <- neptune_init(project="<team/project>",
                    api_token="<token>")
```

I'm getting the following error when running the code above.

```r
Error in this.path::this.path(): 'this.path' used in an inappropriate fashion
* no appropriate source call was found up the calling stack
* R is being run from a shell and argument 'FILE' is missing
Traceback:

1. neptune_init(project="<team/project>",
                    api_token="<token>")
2. this.path::this.path()
3. error("'this.path' used in an inappropriate fashion\n", "* no appropriate source call was found up the calling stack\n", 
 .     "* R is being run from a shell and argument 'FILE' is missing", 
 .     class = this.path_not_exists_error_class)
```

**Comment by abin-tiger** [comment]
looks like the cause of the issue is `interactive()` returning false while running in jupyter notebook in `neptune_init` function.
https://github.com/neptune-ai/neptune-r/blob/37290206ca14730b58d1f326adfb46a62a57c3d4/R/neptune_init.R#L24

**Comment by Blaizzy** [comment]
Hi @abin-tiger,

Thank you for your patience!

I will consult with the devs and come back to you,

**Comment by Blaizzy** [comment]
Hi @abin-tiger 

Sorry for the late reply,

Here is what I found from the devs: 

`neptune-r` is a work in progress. Currently, it does not work so well with Notebooks (Jupyter/Colab) and it's mentioned it in the sample R-based Colab notebook: 
- Colab: https://colab.research.google.com/drive/1NlsoDUhSrNuurRoSQuaRpw3EwQMs1AGt?usp=sharing (# Error in Colab when called with empty file list).
- Docs: https://docs.neptune.ai/integrations-and-supported-tools/languages/neptune-client-r

It's in our backlog to fix this bug!

**Workaround**
Currently, the recommendation for users is to specify some (maybe even non-existent or empty list) of files for `source_files`.

Example:

Failed script ❌ : 
```
neptune::neptune_set_api_token('ANONYMOUS')
run <- neptune::neptune_init(
  project='test',
  mode='sync', # Async seems to be not working in Colab environment
)
```
Successful script ✅ :
```
neptune::neptune_set_api_token('ANONYMOUS')
run <- neptune::neptune_init(
  project='test',
  mode='sync', # Async seems to be not working in Colab environment
  source_files=c('') #or c('sample_data') 
)
```

**Comment by abin-tiger** [comment]
Thank you for checking!

**Comment by Blaizzy** [comment]
Most welcome! 😊

I'm glad I could help. If you need anything else please don't hesitate to let me know.
