### ISSUE TITLE
Native R implementation?

### ISSUE THREAD

**Issue by sebffischer** [neptune-ai/neptune-r#18]
Hello, 

first of all, thank you for your great tool! 

Are there any plans to provide a native R implementation of neptune-ai? 
Currently all DL-tracking packages in R I am aware of depend on reticulate which I would rather like to avoid. 
Do you plan to provide a native R implementation for neptune-ai or will it always be a python wrapper?

Thanks in advanced, 

Sebastian

**Comment by Herudaio** [comment]
Hi @sebffischer! 

We will be sticking with the "powered by Python library" approach for at least the short and mid-term. There is a lot going on under the hood to provide a smooth and reliable experience, and we cannot commit to providing it with R native implementation. We are committed though for the package to feel as R native as possible not just-a-quick-wrapper :)
