### ISSUE TITLE
`this.path()` should be working in Jupyter Notebook

### ISSUE THREAD

**Issue by ArcadeAntics** [neptune-ai/neptune-r#29]
Hiya! I'm the maintainer of **this.path**. I saw issue #16 where someone mentioned that **neptune** was failing because it does not work in a Jupyter Notebook. I have since fixed this as of update **1.3.0**. If it isn't working for whatever reason, I also added **set.this.path.jupyter()** so that your users can explicitly declare the basename of the Jupyter Notebook. Finally, I added **try.this.path()** to get the normalized path of the executing script, the non-normalized path if that fails, and `NA_character_` is that fails as well.  You could change file 'R/neptune_init_run.R' from:

```R
    if (is.null(source_files) & !interactive()) {
      source_files <- c(this.path::this.path())
    }
```

to:

```R
    if (is.null(source_files)) {
      source_files <- this.path::try.this.path()
    }
```

and it should provide the same functionality as before but behave better in Jupyter. 

I'm not sure if it was best to report this as a bug report or as an email, but I figured it would be best as a bug report for other people to see it as well.

I hope this helps!

**Comment by SiddhantSadangi** [comment]
Hello @ArcadeAntics 👋 

Thanks for making the fix and the suggestions. 🚀 
Sorry for the radio silence on this issue.
I've informed our engineering team of this; however, I cannot promise any ETA currently.

I'll reopen this until the fix is implemented so that it is easily visible to others facing the same issue.

Thank you, and have a great day! 🌞

**Comment by ArcadeAntics** [comment]
Hiya @SiddhantSadangi !


I was actually planning a major update **this.path_2.0.0** where I would rename `this.path()` to `sys.path()` along with several other functions; `try.this.path()` is renamed to `try.sys.path()`, `set.this.path.jupyter()` is renamed to `set.sys.path.jupyter()`. This started from some confusion about the misleading function name `this.path()`, you can see that here https://github.com/ArcadeAntics/this.path/issues/13

I did also email the maintainer of R package **neptune** to let them know of these changes, mostly because it has the potential to break this package. I also provided a fix in that email, but maybe it would be better to provide a PR.

Either way, thank you for responding! The wait is no problem.

**Comment by SiddhantSadangi** [comment]
Thanks for the heads-up @ArcadeAntics 🙏 

I've informed our product and engineering teams about this.

**Comment by SiddhantSadangi** [comment]
Closing as both our R and Jupyter integrations have been deprecated for the foreseeable future.
