### ISSUE TITLE
neptune$init errors

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ai/neptune-r#3]
@needlecapter 

When running:

```bash
R CMD build
R CMD check neptune
```

I am getting the following error:

```
> tryCatch(reticulate::install_miniconda(), error=function(e) print('miniconda already installed'))
[1] "miniconda already installed"
> 
> # We are using api token for an anonymous user neptuner. For other projects use your private api token.
> init_neptune(api_token = 'ANONYMOUS', project_name = 'shared/r-integration', python='miniconda', python_path='r-reticulate')
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'neptune' has no attribute 'init'
Calls: init_neptune ... py_get_attr_or_item -> py_get_attr -> py_get_attr_impl
Execution halted

```

**Comment by needlecapter** [comment]
I can't reproduce this on my machine .. can you try changing neptune dir to something like rneptune, maybe reticulate imports dir/file instead of package (returns empty module)? happened to me some time ago on windows

**Comment by jakubczakon** [comment]
Didn't help.

Does it go through cleanly when running?

```R
R CMD build
R CMD check neptune
```

If so, perhaps we should just submit it.

**Comment by needlecapter** [comment]
now I get 'The provided API key is invalid' due to 'ANONYMOUS' key ...
maybe we have to split the key into 
paste0('aaaaaaa',
'bbbbbbbbbbbbbb',
'aaaaaaaaaaaaa')
so the lines are not too long and key is still ok ?

**Comment by jakubczakon** [comment]
I think you  simply need to update neptune-client.

**Comment by needlecapter** [comment]
ok.. that's weird i get either 'invalid api token' OR 'missing api token' even tho NEPTUNE_API_TOKEN is set to 'Anonymous' 
investigating it rn

**Comment by needlecapter** [comment]
if I pass the token directly to neptune$init(api_token = Sys.getenv('NEPTUNE_API_TOKEN')) it works just fine (except for the warning.. any way to supress it as python/reticulate has different stdout/stderr than R so suppressWarnings is not working)
now I get 'Unable to find current active experiment' no matter what I call after the init

**Comment by jakubczakon** [comment]
Hmm, super weird.

**Comment by jakubczakon** [comment]
@needlecapter 
I am trying to run the following:

```R
library("reticulate")
use_condaenv("/home/jakub/miniconda3/envs/docs_env/bin/python")
neptune <- import("neptune")
neptune$init(project_qualified_name='shared/r-integration',
             api_token='ANONYMOUS'
)
```

and it uses pythonn version 2.7 rather than the one I am pointing to (which should be 3.6)

**Comment by jakubczakon** [comment]
@needlecapter 
Ok, so I think I know where the problem is.
When running:

```R
tryCatch(reticulate::install_miniconda(), error=function(e) print('miniconda already installed'))
source('R/neptune.R')

# We are using api token for an anonymous user neptuner. For other projects use your private api token.
init_neptune(api_token = 'ANONYMOUS', 
                     project_name = 'shared/r-integration', 
                     python='miniconda', 
                     python_path="/home/jakub/miniconda3/envs/docs_env/bin/python")
```

it **fails**.

but when I am simply running this:

```R
library("reticulate")
use_condaenv("/home/jakub/miniconda3/envs/docs_env/bin/python")
neptune <- import("neptune")

neptune$init(api_token="ANONYMOUS", project_qualified_name = 'shared/r-integration')
```

It **works** with no problems.

But when I run this:

```R
library("reticulate")
use_condaenv("/home/jakub/miniconda3/envs/docs_env/bin/python")
neptune <- import("neptune")

Sys.setenv('NEPTUNE_API_TOKEN' = "ANONYMOUS")
neptune$init(project_qualified_name = 'shared/r-integration')
```

it **fails** again.

But when I am running:

```R
library("reticulate")
use_condaenv("/home/jakub/miniconda3/envs/docs_env/bin/python")
neptune <- import("neptune")

Sys.setenv('NEPTUNE_API_TOKEN' = "ANONYMOUS")
neptune$init(api_token=Sys.getenv('NEPTUNE_API_TOKEN'), project_qualified_name = 'shared/r-integration')
```

it **works** again.

So I think there is something wrong with setting this `NEPTUNE_API_TOKEN` and/or how the missing value for the argument `api_token` is handled in the `init_neptune`  function.

I think `Sys.setenv` and and `Sys.getenv` happen in the R environment while `neptune$init()` executes it in the Python environment and this `NEPTUNE_API_TOKEN` is missing there.
A simple solution is to go `neptune$init(api_token=Sys.getenv('NEPTUNE_API_TOKEN',...)` I think. 

Perhaps you could rewrite init somehow?
