### ISSUE TITLE
Any chance we can get source logging?

### ISSUE THREAD

**Issue by andrewcstewart** [neptune-ai/neptune-r#4]
`log_source()` or equivalent ?

**Comment by andrewcstewart** [comment]
Actually, judging from the python-api it looks like this would be an option in `create_experiment`.

```
create_experiment(name = "default",
                  params = reticulate::dict(),
                  tags =  c(),
                  upload_source_files = c(rstudioapi::getActiveDocumentContext()$path)
)
```

**Comment by pitercl** [comment]
Hi @andrewcstewart , yes, as you wrote - the `upload_source_files` param is the way to go here. You can take a look at an example code here: https://ui.neptune.ai/shared/r-integration/e/RIN-44/source-code?file=train_random_forest.R

**Comment by andrewcstewart** [comment]
https://github.com/neptune-ai/neptune-r/pull/5

**Comment by HubertJaworski** [comment]
Hi, we reviewed your code and merged it - it'll be released soon
